export const STARSHIPS_URL = "https://swapi.dev/api/starships"
export const CHARACTERS_URL = "https://swapi.dev/api/people/"
export const PLANETS_URL = "https://swapi.dev/api/planets/"
export const FILMS_URL = "https://swapi.dev/api/films/" 
export const SPECIES_URL = "https://swapi.dev/api/species/" 
export const VEHICLES_URL = "https://swapi.dev/api/vehicles/"